language: node_js
node_js:
  - 'stable'
before_script:
  - npm install
script:
  - npm run build
  - cp package.json dist/
  - cp README.md dist/
  - cd dist/
after_success:
  - npm version patch
  - git add .
  - git commit -m 'bump patch version'
  - git push origin master
deploy:
  provider: npm
  email: $EMAIL
  api_key:
    secure: $NPM
  skip_cleanup: true
  on:
    branch: master
